$htmlPath = "..\V5\pages\product-info.html"
$content = Get-Content -Raw $htmlPath
$content = $content -replace '<div class="sec reveal">', '<div class="glass-sec reveal">'
$content = $content -replace '(<div class="wrap">\s*)', "${1}<!-- ANATOMY INTERACTIVE --><div class="glass-sec reveal"><div class="sec-eye">Interactive Breakdown</div><div class="sec-title">The Anatomy of Authenticity</div><div class="sec-rule"></div><div class="anatomy-container"><img src="../assets/images/100s1.jpg" alt="100 Prop Bill Interactive" class="anatomy-img"><div class="hotspot" style="top: 50%; left: 10%;"><div class="hotspot-tooltip"><h4>BOPP Substrate</h4><p>The base polymer material providing the authentic snap and feel.</p></div></div><div class="hotspot" style="top: 30%; left: 85%;"><div class="hotspot-tooltip"><h4>Integrated Window</h4><p>Chemically bonded transparent window, perfectly flush with the surface.</p></div></div><div class="hotspot" style="top: 80%; left: 15%;"><div class="hotspot-tooltip"><h4>Raised Braille</h4><p>Palpable raised dots for an unmatched tactile realism.</p></div></div><div class="hotspot" style="top: 15%; left: 50%;"><div class="hotspot-tooltip"><h4>Micro-Printing</h4><p>Razor-sharp text visible only under 10x magnification.</p></div></div></div></div>

"
$content = $content -replace '(?s)(<!-- PRINTING -->.*?</div>\s*</div>\s*</div>)', "${1}

<!-- UV SLIDER --><div class="glass-sec reveal"><div class="sec-eye">Ultraviolet Reaction</div><div class="sec-title">Security Features Under UV</div><div class="sec-rule"></div><p class="sec-desc" style="margin-bottom:20px;">Drag the slider to see how our proprietary UV-cured inks react under 365nm ultraviolet light.</p><div class="uv-slider-container" id="uv-slider"><img src="../assets/images/100s1.jpg" alt="Normal Light" class="uv-img-normal"><img src="../assets/images/100s1.jpg" alt="UV Light" class="uv-img-uv" id="uv-layer" style="filter: hue-rotate(180deg) brightness(0.5) contrast(2) saturate(1.5);"><div class="uv-slider-handle" id="uv-handle"></div></div></div>"
$content = $content -replace '(<!-- CTA -->)', "<!-- TECH SPECS --><div class="glass-sec reveal"><div class="sec-eye">Specifications</div><div class="sec-title">Technical Data Sheet</div><div class="sec-rule"></div><div class="spec-table-container"><table class="spec-table"><tr><td>Dimensions</td><td>152.4 mm x 69.85 mm (Exact Canadian Format)</td></tr><tr><td>Weight</td><td>~0.9g per note</td></tr><tr><td>Substrate Material</td><td>Biaxially Oriented Polypropylene (BOPP)</td></tr><tr><td>Print Technology</td><td>UV-Cured CMYK + Intaglio Simulation (Thermal Overprint)</td></tr><tr><td>Optics</td><td>98% Transparent Window + Gold-to-Emerald Hologram Foil</td></tr><tr><td>Durability</td><td>100% Water-Resistant, High Tear Resistance, Dryer-Safe</td></tr></table></div></div><!-- COMPLIANCE --><div class="glass-sec reveal"><div class="compliance-box"><div class="compliance-icon">???</div><div class="compliance-text"><h3>100% Legal & Safe for Production</h3><p>Our prop bills are engineered specifically for film, television, and media production. They strictly comply with Canadian and US regulations for prop currency.</p><p><strong>Key Compliance Features:</strong> Mandatory "PROP USE ONLY" markings, non-magnetic inks, slightly altered scale/design nuances invisible on camera, and one-sided holographic simulation to prevent counterfeiting issues.</p></div></div></div>

${1}"
$js = "<script>document.addEventListener('DOMContentLoaded', () => { const slider = document.getElementById('uv-slider'); const handle = document.getElementById('uv-handle'); const uvLayer = document.getElementById('uv-layer'); if(slider) { let isDragging = false; const updateSlider = (e) => { if(!isDragging) return; const rect = slider.getBoundingClientRect(); let x = e.clientX || (e.touches && e.touches[0].clientX); if(x === undefined) return; let percent = ((x - rect.left) / rect.width) * 100; percent = Math.max(0, Math.min(100, percent)); uvLayer.style.clipPath = 'polygon(0 0, ' + percent + '% 0, ' + percent + '% 100%, 0 100%)'; handle.style.left = percent + '%'; }; slider.addEventListener('mousedown', () => isDragging = true); slider.addEventListener('touchstart', () => isDragging = true); window.addEventListener('mouseup', () => isDragging = false); window.addEventListener('touchend', () => isDragging = false); window.addEventListener('mousemove', updateSlider); window.addEventListener('touchmove', updateSlider); } });</script></body>"
$content = $content -replace '</body>', $js
Set-Content -Path $htmlPath -Value $content -NoNewline
